# Generated by Django 5.1.2 on 2024-11-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_post2_delete_carusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
