# Generated by Django 5.1.2 on 2024-11-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_firstpost_secondpost_delete_post_delete_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstpost',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
