# Generated by Django 5.1.2 on 2024-11-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_firstpost_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FirstPost',
        ),
        migrations.DeleteModel(
            name='SecondPost',
        ),
    ]
