# Generated by Django 5.1.2 on 2024-11-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_post_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title2',
            field=models.CharField(max_length=200),
        ),
    ]
