# Generated by Django 5.1.2 on 2024-11-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_post_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_card',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='text_card',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title_card',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
