# Generated by Django 5.1.2 on 2024-12-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_post_img_card_post_text_card_post_title_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField()),
                ('title2', models.CharField(max_length=200)),
                ('text2', models.TextField()),
                ('img_card', models.ImageField(blank=True, upload_to='')),
                ('title_card', models.CharField(max_length=200)),
                ('text_card', models.TextField()),
            ],
        ),
    ]
