# Generated by Django 5.1.2 on 2024-12-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_mir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mir',
            name='img_card',
        ),
        migrations.RemoveField(
            model_name='mir',
            name='text_card',
        ),
        migrations.RemoveField(
            model_name='mir',
            name='title_card',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_card',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_card',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_card',
        ),
    ]
